# 
# GitHub Action to build and deploy the static site to a staging URL
# 
name: Deploy Staging
'on':
  # Trigger on code pushed to the staging branch
  push:
    branches:
      - staging

  # Trigger on Contentful webhook
  repository_dispatch:
    types:
      - ctf-master-save

  # Allow manual trigger from the Actions tab on github.com
  workflow_dispatch:

concurrency: 
  group: staging
  cancel-in-progress: true
  
jobs:
  build_and_deploy:
    name: Build static website
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'staging'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate static website
        run: npm run generate
        env:
          SITE_TITLE: Space Between Therapy
          CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
          CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SBT }}'
          channelId: staging
          projectId: spacebetweentherapy-d8430
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels