# 
# GitHub Action to build and deploy the static site to a temporary test URL
# 
name: Deploy PR
'on':
  # Trigger on code pull request
  pull_request:

  # Allow manual trigger from the Actions tab on github.com
  workflow_dispatch:
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      SITE_TITLE: Space Between Therapy
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install && npm install -g @lhci/cli@0.8.x chromium

      - name: Generate static website
        run: SITE_TITLE=$SITE_TITLE CTF_SPACE_ID=${{ secrets.CTF_SPACE_ID }} CTF_CDA_ACCESS_TOKEN=${{ secrets.CTF_CDA_ACCESS_TOKEN }} npm run generate
      
      - name: Run Lighthouse
        run:  LHCI_GITHUB_APP_TOKEN=${{ secrets.LHCI_GITHUB_APP_TOKEN }} lhci autorun

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SBT }}'
          projectId: spacebetweentherapy-d8430
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels