name: Deploy STAGING
'on':
  push:
    branches:
      - staging
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      SITE_TITLE: Space Between Therapy
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && SITE_TITLE=$SITE_TITLE CTF_SPACE_ID=${{ secrets.CTF_SPACE_ID }} CTF_CDA_ACCESS_TOKEN=${{ secrets.CTF_CDA_ACCESS_TOKEN }} npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SBT }}'
          channelId: staging
          projectId: spacebetweentherapy-d8430
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels