# 
# GitHub Action to build and deploy the static site to the production URL
# 
name: Deploy Production
'on':
  # Trigger on code pushed to the main branch
  push:
    branches:
      - main

  # Trigger on Contentful webhook
  repository_dispatch:
    types:
      - ctf-master-publish

  # Allow manual trigger from the Actions tab on github.com
  workflow_dispatch:

concurrency: 
  group: production
  cancel-in-progress: true
  
jobs:
  build_and_deploy:
    name: Build static website
    runs-on: ubuntu-latest
    environment: live

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate static website
        run: npm run generate
        env:
          SITE_TITLE: Space Between Therapy
          CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
          CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SBT }}'
          channelId: live
          projectId: spacebetweentherapy-d8430
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
